<?php

/**
 * translation file
 * 
 * @package    account
 */
$_COS_LANG_MODULE['Create Account'] = 'Opret konto';

# account module
$_COS_LANG_MODULE['Edit Account'] = 'Rediger konto';
$_COS_LANG_MODULE['List Users'] = 'Vis konti';
$_COS_LANG_MODULE['Welcome to the account module'] =  "Velkommen til konto sektionen";


$_COS_LANG_MODULE['Request Password'] = 'Glemt password?';
$_COS_LANG_MODULE['Enter password'] = 'Indtast password';
$_COS_LANG_MODULE['Username'] = 'Brugernavn';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Retype Password'] = 'Gentag Password';
$_COS_LANG_MODULE['Get an user account by filling out the following form'] = 'Få en bruger konto ved at udfylde den følgende form';

$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Passwords does not match'] = 'De to passwords er ikke ens';
$_COS_LANG_MODULE['Username exists. Pick another'] = 'Brugernavn eksisterer. Vælg et andet';
$_COS_LANG_MODULE['Not a valid email'] = 'Det er ikke en gyldig email';
$_COS_LANG_MODULE['You are logged in'] = 'Du er logget på';
$_COS_LANG_MODULE['Logout'] = 'Log ud';
$_COS_LANG_MODULE['Login'] = 'Log ind';
$_COS_LANG_MODULE['Login or logout'] = 'Log ind eller log ud';
$_COS_LANG_MODULE['Wrong email or password'] = 'Forkert brugernavn eller password';

$_COS_LANG_MODULE['Error'] = 'Fejl';

$_COS_LANG_MODULE['Username can only contain alphabetic chars and number and . and _'] = 'Breugernavn kan kun indholde bogstaver samt . and _';
$_COS_LANG_MODULE['Username should be at least 5 chars long'] = 'Brugernavn skal mindst være fem karakterer langt';
$_COS_LANG_MODULE['Password should be at least 5 chars long'] = 'Password skal mindst være fem karakterer langt';
$_COS_LANG_MODULE['Login info sent to'] = 'Information om log ind er sendt til';
$_COS_LANG_MODULE['No such email'] = 'Den indtastede email eksisterer ikke';
$_COS_LANG_MODULE['Enter email to require lost password'] = 'Indtast email for at få log ind oplysninger';
$_COS_LANG_MODULE['Email already exists.'] = 'Email eksister allerede i systmet';
$_COS_LANG_MODULE['New account has been created'] = 'Ny konto er blevet oprettet. Få at logge ind må du besøge din mail box og følge instruktionerne';
$_COS_LANG_MODULE['Set New Password'] = 'Indtast nyt password';
$_COS_LANG_MODULE['New passwords has been set'] = 'Nyt password er gemt';
$_COS_LANG_MODULE['No such combination between user and validation key'] = 'Ingen sådan kombination mellem brugernavn validerings nøgle';
$_COS_LANG_MODULE['Set your new password'] = 'Set your new password';

$_COS_LANG_MODULE['Not Admin'] = 'Ikke admin';
$_COS_LANG_MODULE['Verified'] = 'Godkendt';
$_COS_LANG_MODULE['Not Verified'] = 'Ikke godkendt';
$_COS_LANG_MODULE['List Users'] = 'Vis brugere';
$_COS_LANG_MODULE['Edit User'] = 'Rediger bruger';
$_COS_LANG_MODULE['User Updated'] = 'Bruger opdateret';
$_COS_LANG_MODULE['Edit User Account'] = 'Rediger bruger konto';
$_COS_LANG_MODULE['Is Admin'] = 'Er admin';
$_COS_LANG_MODULE['Delete User'] = 'Slet bruger';
$_COS_LANG_MODULE['User Deleted'] = 'Bruger slettet';

#signup messages
$_COS_LANG_MODULE['signup'] = "Velkommen !username!\n\n";
$_COS_LANG_MODULE['signup'].= "Du har oprettet en konto på !site_name!\n";
$_COS_LANG_MODULE['signup'].= "For at fuldføre oprettelse af din konto skal du klikke på\n";
$_COS_LANG_MODULE['signup'].= "følgende link eller klippe det ind i browserens adresse linie\n\n";
$_COS_LANG_MODULE['signup'].= "!verify_key!\n\n";
$_COS_LANG_MODULE['signup_subject'] = "Konto oprettelse på !site_name!";


$_COS_LANG_MODULE['request_pw'] = "Hej !username!\n\n";
$_COS_LANG_MODULE['request_pw'].= "Du har fået denne mail fra !site_name! fordi du har mistet\n";
$_COS_LANG_MODULE['request_pw'].= "dit password. For at få en nyt password må du besøge ";
$_COS_LANG_MODULE['request_pw'].= "følgende link eller klippe det ind i browserens adresse linie\n\n";
$_COS_LANG_MODULE['request_pw'].= "!verify_key!\n\n";
$_COS_LANG_MODULE['request_pw_subject'] = "Opret nyt password på !site_name!";

$_COS_LANG_MODULE['Incorrect answer to captcha test'] = 'Forkert svar til captcha test';
$_COS_LANG_MODULE['Account has been verified. You may log in'] = 'Din konto er verificeret. Du må logge ind nu';

$_COS_LANG_MODULE['Is Super'] = 'Er Super';

$_COS_LANG_MODULE['use_open_id'] = 'Log ind med OpenID';
$_COS_LANG_MODULE['login_open_id'] = 'Login med OpenID';
$_COS_LANG_MODULE['your_open_id'] = 'Dit openID';

$_COS_LANG_MODULE['openid_loggedin_message'] = 'Du er logget ind!';
$_COS_LANG_MODULE['openid_user_logged_in'] = 'Du er logget ind med openID';



$_COS_LANG_MODULE['list_openids'] = 'Vis brugere med openID';

$_COS_LANG_MODULE['Super'] = 'Super';
$_COS_LANG_MODULE['Not Super'] = 'Ikke Super';

$_COS_LANG_MODULE['openid'] = 'openID';
$_COS_LANG_MODULE['logged_in_with_email'] =  'Du er logget på med email';

$_COS_LANG_MODULE['logged_in_with_openid'] = 'Du er logget på med openID';

$_COS_LANG_MODULE['no_valid_open_id_url'] = 'Ingen gyldig openid url';
$_COS_LANG_MODULE['openid_login_failed'] = 'openID login fejlede';

$_COS_LANG_MODULE['keep_session'] = 'Forbliv logget ind de næste';

$_COS_LANG_MODULE['days'] = 'dage';


$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Verify Account'] = 'Verify Account';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Account Admin'] = 'Account Admin';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['openid_valid_login'] = 'Korrekt OpenID';
$_COS_LANG_MODULE['openid_account_created'] = 'OpenID konto skabt';
$_COS_LANG_MODULE['openid_invalid_login'] = 'Ikke korrekt OpenID login';
$_COS_LANG_MODULE['openid_login_cancelled'] = 'OpenID login afbrudt';
$_COS_LANG_MODULE['Submit'] = 'Send';

$_COS_LANG_MODULE['logged_in_with_facebook'] = 'Logget ind med facebook';
$_COS_LANG_MODULE['account_urlid'] = 'URL ID';
$_COS_LANG_MODULE['logged_in_with_alternative'] = 'Logget ind som';

$_COS_LANG_MODULE['facebook_login'] = 'Log ind med facebook';
$_COS_LANG_MODULE['Select Provider'] = 'Vælg udbyder';
$_COS_LANG_MODULE['account_openid_select_provider'] = 'Vælg open ID udbyder';

$_COS_LANG_MODULE['account_openid_select_openid_provider'] = 'Open ID udbyder';

$_COS_LANG_MODULE['openid_login'] = 'Open ID Login';
