<?php

// Translation of file /home/dennis/www/oscmsdk/modules/account/create/verify.php

$_COS_LANG_MODULE['account_title_verify_account'] = 'Verificer Konto';
$_COS_LANG_MODULE['account_is_already_verified'] = 'Konto er allerede verificeret';
$_COS_LANG_MODULE['account_has_been_verified'] = 'Konto er blevet verificeret';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/index.php

$_COS_LANG_MODULE['account_create_index_title'] = 'Opret konto';
$_COS_LANG_MODULE['account_create_account_has_been_created'] = 'Konto er blevet oprettet. 
Du vil modtage en email i løbet af kort tid.     
Tryk et link i denne mail og du er verificeret.';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/model.create.inc

$_COS_LANG_MODULE['account_error_email_exists'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['account_error_password_length'] = 'Password skal mindst være 7 karaktere langt';
$_COS_LANG_MODULE['account_error_password_mismatch'] = 'Passwords stemmer ikke overens';
$_COS_LANG_MODULE['account_error_invalid_email'] = 'Ugyldig email';
$_COS_LANG_MODULE['account_error_incorrect_captcha'] = 'Ikke et korrekt svar til captcha';
$_COS_LANG_MODULE['account_signup_subject'] = 'Oprettelse af konto på';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/view.create.inc

$_COS_LANG_MODULE['account_user_create_legend'] = 'Opret konto';
$_COS_LANG_MODULE['account_email_label'] = 'Email';
$_COS_LANG_MODULE['account_password_label'] = 'Password';
$_COS_LANG_MODULE['account_retype_password_label'] = 'Gentag password';
$_COS_LANG_MODULE['account_submit'] = 'Send';
// Translation of file /home/dennis/www/oscmsdk/modules/account/view.account.inc

$_COS_LANG_MODULE['account_welcome_message'] = 'Velkommen';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/index.php

$_COS_LANG_MODULE['account_facebook_login'] = 'Facebook login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/model.facebook.inc

$_COS_LANG_MODULE['account_logged_in_with_email'] = 'Logget ind med email';
$_COS_LANG_MODULE['account_logged_in_with_facebook'] = 'Logget ind med facebook';
$_COS_LANG_MODULE['account_logout'] = 'Log ud';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/index.php

$_COS_LANG_MODULE['account_login_or_logout'] = 'Log ind eller ud';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/model.login.inc

$_COS_LANG_MODULE['account_login_wrong_username_password'] = 'Enten forkert password eller email';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/view.login.inc

$_COS_LANG_MODULE['account_form_email'] = 'Email';
$_COS_LANG_MODULE['account_form_password'] = 'Password';
$_COS_LANG_MODULE['account_keep_session'] = 'Forbliv logget ind';
$_COS_LANG_MODULE['account_num_days'] = 'dage';
$_COS_LANG_MODULE['account_logged_in_with_alternative'] = 'Logget in med alternativ til email';
// Translation of file /home/dennis/www/oscmsdk/modules/account/index.php

$_COS_LANG_MODULE['account_title_index'] = 'Konto';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/verify.php

$_COS_LANG_MODULE['account_request_set_new_passwords_title'] = 'Nyt password';
$_COS_LANG_MODULE['account_request_new_password_has_been_set'] = 'Nyt password er blevet gemt';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/view.request_pw.inc

$_COS_LANG_MODULE['account_enter_email_to_recover_lost_password'] = 'Indtast din email for at genskabe password';
$_COS_LANG_MODULE['account_request_legend_set_new_password'] = 'Indtast nyt password';
$_COS_LANG_MODULE['account_form_retype_password'] = 'Gentag password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/index.php

$_COS_LANG_MODULE['account_request_password_title'] = 'Opret nyt password';
$_COS_LANG_MODULE['account_request_login_info_sent_to'] = 'Check din email. Heri er der instruktioner til at 
    skabe et nyt password.';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/model.request_pw.inc

$_COS_LANG_MODULE['account_error_no_such_email'] = 'Ingen sådan email i systemet';
$_COS_LANG_MODULE['account_request_pw_subject_for_site'] = 'Genskabelse af password';
$_COS_LANG_MODULE['account_password_length_error'] = 'Password skal mindst være syv karakterer langt';
$_COS_LANG_MODULE['account_password_no_match'] = 'De to password er ikke ens';
$_COS_LANG_MODULE['account_request_no_combination_md5_user'] = 'Ingen sådan kombination mellem bruger id og validerings kode';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/views/login.inc

$_COS_LANG_MODULE['account_openid_select_provider'] = 'Vælg udbyder';
$_COS_LANG_MODULE['account_openid_enter_provider'] = 'Log ind med open ID';
$_COS_LANG_MODULE['account_openid_openid_provider_options'] = 'Options';
$_COS_LANG_MODULE['account_login_open_id_legend'] = 'Log ind med open ID';
$_COS_LANG_MODULE['account_open_id_your_open_id_form'] = 'Dit open ID';
$_COS_LANG_MODULE['account_keep_session'] = 'Forbliv logget ind';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/index.php

$_COS_LANG_MODULE['account_openid_login_index'] = 'open ID login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/model.openid.inc

$_COS_LANG_MODULE['account_no_valid_open_id_url'] = 'Ikke en gyldig open ID URL';
$_COS_LANG_MODULE['account_openid_valid_login'] = 'Gyldigt login';
$_COS_LANG_MODULE['account_openid_account_created'] = 'Open ID konto oprettet';
$_COS_LANG_MODULE['account_openid_loggedin_message'] = 'Logget ind med open ID';
$_COS_LANG_MODULE['account_openid_invalid_login'] = 'Ugyldigt login';
$_COS_LANG_MODULE['account_openid_login_cancelled'] = 'Login afbrudt';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/model.admin.inc

$_COS_LANG_MODULE['account_password_error_length'] = 'Password ksla mindst være 7 karakterer langt';
$_COS_LANG_MODULE['account_password_dont_match'] = 'Passwords matcher ikke';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/list.php

// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/delete.php

$_COS_LANG_MODULE['account_delete_account_title'] = 'Slet Konto';
$_COS_LANG_MODULE['account_has_been_deleted'] = 'Konto er blevet slettet';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/index.php

$_COS_LANG_MODULE['account_index_title'] = 'Konto';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/view.admin.inc

$_COS_LANG_MODULE['account_edit_legend'] = 'Ret konto';
$_COS_LANG_MODULE['account_email'] = 'Email';
$_COS_LANG_MODULE['account_password'] = 'Password';
$_COS_LANG_MODULE['account_password_repeat'] = 'Gentag password';
$_COS_LANG_MODULE['account_is_verfied'] = 'Verificere';
$_COS_LANG_MODULE['account_is_admin'] = 'Admin';
$_COS_LANG_MODULE['account_is_super'] = 'Super';
$_COS_LANG_MODULE['account_form_is_verified'] = 'Er verificeret';
$_COS_LANG_MODULE['account_form_is_admin'] = 'Admin';
$_COS_LANG_MODULE['account_form_is_super'] = 'Super';
$_COS_LANG_MODULE['account_update'] = 'Opdater';
$_COS_LANG_MODULE['account_is_not_admin'] = 'Ikke admin';
$_COS_LANG_MODULE['account_is_not_super'] = 'ikke super';
$_COS_LANG_MODULE['account_is_verified'] = 'Er verificeret';
$_COS_LANG_MODULE['account_is_not_verified'] = 'Ikke verificeret';
$_COS_LANG_MODULE['account_edit'] = 'Ret';
$_COS_LANG_MODULE['account_delete'] = 'Slet';
$_COS_LANG_MODULE['account_delete_account_legend'] = 'Slet konto';
$_COS_LANG_MODULE['account_delete_label'] = 'Slet';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/edit.php

$_COS_LANG_MODULE['account_edit_account_title'] = 'Ret konto';
$_COS_LANG_MODULE['account_action_user_updated'] = 'Konto opdateret';

$_COS_LANG_MODULE['account_login_will_not_be_displayed'] = 'Vil ikke blive vist';
$_COS_LANG_MODULE['account_no_screenname'] = 'Intet skærm navn';
$_COS_LANG_MODULE['account_your_screenname_is'] = 'Dit skærm navn er';
$_COS_LANG_MODULE['account_legend_edit_account'] = 'Ret konto';
$_COS_LANG_MODULE['account_form_openid'] = 'Open ID';
$_COS_LANG_MODULE['account_form_username'] = 'Brugernavn';
$_COS_LANG_MODULE['account_form_password_retype'] = 'Gentag password';
$_COS_LANG_MODULE['account_form_submit'] = 'Send';
$_COS_LANG_MODULE['account_delete_user_legend'] = 'Slet Bruger';

$_COS_LANG_MODULE['account_login_legend'] = 'Log ind';

$_COS_LANG_MODULE['account_openid_login_failed'] = 'OpenID login mislykkedes. Check openID URL';
$_COS_LANG_MODULE['account_logged_in_with_open_id'] = 'Logget ind med OpenID';