<?php

// Translation of file /home/dennis/www/oscmsdk/modules/account/create/verify.php

$_COS_LANG_MODULE['Verify Account'] = 'Verificer Konto';
$_COS_LANG_MODULE['Account is already verified'] = 'Konto er allerede verificeret';
$_COS_LANG_MODULE['Account has been verified'] = 'Konto er blevet verificeret. Du kan nu <a href="/account/login/index">logge ind</a>';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/index.php

$_COS_LANG_MODULE['Create Account'] = 'Opret konto';
$_COS_LANG_MODULE['Account: Create notice'] = 'Konto er blevet oprettet. 
Du vil modtage en email i løbet af kort tid.     
Tryk et link i denne mail og du er verificeret.';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/model.create.inc

$_COS_LANG_MODULE['Email already exists'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['Password has to be at least 7 chars'] = 'Password skal mindst være 7 karaktere langt';
$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords stemmer ikke overens';
$_COS_LANG_MODULE['Invalid email'] = 'Ugyldig email';
$_COS_LANG_MODULE['Wrong answer to captcha test'] = 'Ikke et korrekt svar til captcha';
$_COS_LANG_MODULE['Confirm account'] = 'Oprettelse af konto på';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/view.create.inc

$_COS_LANG_MODULE['Create account'] = 'Opret konto';
$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Repeat password'] = 'Gentag password';
$_COS_LANG_MODULE['Send'] = 'Send';
// Translation of file /home/dennis/www/oscmsdk/modules/account/view.account.inc

$_COS_LANG_MODULE['You can now log in'] = 'Velkommen';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/index.php

$_COS_LANG_MODULE['Facebook Login'] = 'Facebook login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/model.facebook.inc

$_COS_LANG_MODULE['Logged in with email'] = 'Logget ind med email';
$_COS_LANG_MODULE['Logged in with facebook'] = 'Logget ind med facebook';

// Translation of file /home/dennis/www/oscmsdk/modules/account/login/index.php

$_COS_LANG_MODULE['Log in or Log out'] = 'Log ind eller ud';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/model.login.inc

$_COS_LANG_MODULE['Not a correct email or password'] = 'Enten forkert password eller email';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/view.login.inc

$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Let me stay logged in'] = 'Forbliv logget ind';
$_COS_LANG_MODULE['days'] = 'dage';
$_COS_LANG_MODULE['Logged in as'] = 'Logget in med alternativ til email';
// Translation of file /home/dennis/www/oscmsdk/modules/account/index.php

$_COS_LANG_MODULE['Account'] = 'Konto';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/verify.php

$_COS_LANG_MODULE['Create new password'] = 'Nyt password';
$_COS_LANG_MODULE['New password has been saved'] = 'Nyt password er blevet gemt';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/view.request_pw.inc

$_COS_LANG_MODULE['Enter email to recreate password'] = 'Indtast din email for at genskabe password';
$_COS_LANG_MODULE['Enter new password'] = 'Indtast nyt password';
$_COS_LANG_MODULE['Repeat new password'] = 'Gentag password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/index.php

$_COS_LANG_MODULE['Request new password'] = 'Opret nyt password';
$_COS_LANG_MODULE['Visit your mailbox and follow instructions in order to get a new password'] = 'Check din email. Heri er der instruktioner til at 
    skabe et nyt password.';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/model.request_pw.inc

$_COS_LANG_MODULE['Email does not exists in our system'] = 'Ingen sådan email i systemet';
$_COS_LANG_MODULE['Create new password for site'] = 'Genskabelse af password';
$_COS_LANG_MODULE['Password has to be at least 7 chars'] = 'Password skal mindst være syv karakterer langt';
$_COS_LANG_MODULE['Passwords does not match'] = 'De to password er ikke ens';
$_COS_LANG_MODULE['No such combination between token and email. You can only use the token one time'] = 'Ingen sådan kombination mellem bruger id og validerings kode';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/views/login.inc

$_COS_LANG_MODULE['Select provider'] = 'Vælg udbyder';
$_COS_LANG_MODULE['Log in with openID'] = 'Log ind med openID';
$_COS_LANG_MODULE['Choose provider'] = 'Options';
$_COS_LANG_MODULE['Log in with openID'] = 'Log ind med openID';

$_COS_LANG_MODULE['Let me stay logged in'] = 'Forbliv logget ind';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/index.php

$_COS_LANG_MODULE['OpenID login'] = 'open ID login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/model.openid.inc

$_COS_LANG_MODULE['OpenID login accepted'] = 'Gyldigt login';
$_COS_LANG_MODULE['Logged ind with openID'] = 'Logget ind med openID';
$_COS_LANG_MODULE['Invalid openID'] = 'Ugyldigt login';
$_COS_LANG_MODULE['OpenID Login was cancelled'] = 'Login afbrudt';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/model.admin.inc


$_COS_LANG_MODULE['Login'] = 'Log ind';

$_COS_LANG_MODULE['Logout'] = 'Log ud';
$_COS_LANG_MODULE['Login using facebook'] = 'Log ind';



$_COS_LANG_MODULE['Github login'] = 'Github login';

$_COS_LANG_MODULE['Email already exists in system'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['Invalid login. We need a valid OpenID email'] = 'Ikke en gyldig email';
$_COS_LANG_MODULE['Email already exists in system'] = 'Email eksisterer allerede';

$_COS_LANG_MODULE['Account needs to be verified before you may log in'] = 'Konto skal verificeres før du kan logge ind';
$_COS_LANG_MODULE['This account has been locked'] = 'Konto er låst';



$_COS_LANG_MODULE['Email already exists in system'] = 'Email eksisterer allerede';

$_COS_LANG_MODULE['Hej'] = 'Hej';
$_COS_LANG_MODULE['Du har henvendt dig på'] = 'Du har henvendt dig på';
$_COS_LANG_MODULE['fordi du har mistet
dit password'] = 'fordi du har mistet
dit password';
$_COS_LANG_MODULE['For at genskabe dit password bedes du trykke på det
følgende link eller indsætte det i din browsers addresse linie'] = 'For at genskabe dit password bedes du trykke på det
følgende link eller indsætte det i din browsers addresse linie';
$_COS_LANG_MODULE['Hvis du ikke har forespurgt et nyt password, kan du se bort fra denne
henvendelse'] = 'Hvis du ikke har forespurgt et nyt password, kan du se bort fra denne
henvendelse';

$_COS_LANG_MODULE['Password is too short'] = 'Password is too short';
$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords does not match';
$_COS_LANG_MODULE['Admin index'] = 'Admin index';
$_COS_LANG_MODULE['Edit account'] = 'Edit account';
$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Repeat password'] = 'Repeat password';
$_COS_LANG_MODULE['Account is verified'] = 'Account is verified';
$_COS_LANG_MODULE['Account is admin'] = 'Account is admin';
$_COS_LANG_MODULE['Account is super'] = 'Account is super';
$_COS_LANG_MODULE['Account is locked'] = 'Account is locked';
$_COS_LANG_MODULE['Update account'] = 'Update account';
$_COS_LANG_MODULE['Delete account'] = 'Delete account';
$_COS_LANG_MODULE['ID'] = 'ID';
$_COS_LANG_MODULE['Account is not admin'] = 'Account is not admin';
$_COS_LANG_MODULE['Account is super user'] = 'Account is super user';
$_COS_LANG_MODULE['Account is not super user'] = 'Account is not super user';
$_COS_LANG_MODULE['Account is not verified'] = 'Account is not verified';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Search accounts'] = 'Search accounts';
$_COS_LANG_MODULE['Search account ID'] = 'Search account ID';
$_COS_LANG_MODULE['Edit account'] = 'Edit account';
$_COS_LANG_MODULE['Account has been updated'] = 'Account has been updated';
$_COS_LANG_MODULE['Found the following accounts'] = 'Found the following accounts';
$_COS_LANG_MODULE['I could not find any matching results'] = 'I could not find any matching results';
$_COS_LANG_MODULE['Search for users'] = 'Search for users';
$_COS_LANG_MODULE['Delete account'] = 'Delete account';
$_COS_LANG_MODULE['Account has been deleted'] = 'Account has been deleted';
$_COS_LANG_MODULE['Email already exists'] = 'Email already exists';
$_COS_LANG_MODULE['That is not a valid email'] = 'That is not a valid email';
$_COS_LANG_MODULE['Incorrect answer to captcha test'] = 'Incorrect answer to captcha test';
$_COS_LANG_MODULE['Password needs to be 7 chars'] = 'Password needs to be 7 chars';
$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords does not match';
$_COS_LANG_MODULE['Emails does not match'] = 'Emails does not match';
$_COS_LANG_MODULE['Account created'] = 'Account created';
$_COS_LANG_MODULE['Wrong validation key on account creation'] = 'Wrong validation key on account creation';
$_COS_LANG_MODULE['Email already exists'] = 'Email already exists';
$_COS_LANG_MODULE['Confirm account creation'] = 'Confirm account creation';
$_COS_LANG_MODULE['Hi'] = 'Hi';
$_COS_LANG_MODULE['You have connected with'] = 'You have connected with';
$_COS_LANG_MODULE['because you have lost
your password'] = 'because you have lost
your password';
$_COS_LANG_MODULE['In order to create a new password just press the
following link or paste it into your browsers URL line'] = 'In order to create a new password just press the
following link or paste it into your browsers URL line';
$_COS_LANG_MODULE['If you have not requested a new password then you can just delete
this message'] = 'If you have not requested a new password then you can just delete
this message';
