<?php

// Translation of menu file /home/dennis/www/oscmsdk/modules/account/menu.inc

$_COS_LANG_MODULE['account_login_with_email'] = 'Login med email';
$_COS_LANG_MODULE['account_create_email_account'] = 'Opret email konto';
$_COS_LANG_MODULE['account_request_password'] = 'Mistet password?';
$_COS_LANG_MODULE['account_use_open_id'] = 'OpenID';
$_COS_LANG_MODULE['account_login_facebook'] = 'Facebook';
$_COS_LANG_MODULE['account_admin'] = 'Admin';
// Translation of menu file /home/dennis/www/oscmsdk/modules/account/admin/menu.inc

$_COS_LANG_MODULE['account_list_users'] = 'Vis konti';
$_COS_LANG_MODULE['Account'] = 'Konto';


