<?php


/**
 * translation file
 *
 * @package    account
 */
$_COS_LANG_MODULE['Account'] = 'Konto';
$_COS_LANG_MODULE['account_login_with_email'] = 'Login med email';
$_COS_LANG_MODULE['account_use_open_id'] = 'Login med OpenID';
$_COS_LANG_MODULE['account_login_facebook'] = 'Logind med facebook';
$_COS_LANG_MODULE['account_admin'] = 'Admin';
$_COS_LANG_MODULE['account_list_users'] = 'Vis brugere';
$_COS_LANG_MODULE['account_list_openids'] = 'Vis openIDs';
$_COS_LANG_MODULE['account_create_email_account'] = 'Opret konto med email';
$_COS_LANG_MODULE['account_request_password'] = 'Glemt password?';


