<?php

$_COS_LANG_MODULE['Search for users'] = '搜索用户';
$_COS_LANG_MODULE['Lost password'] = '忘记密码';
$_COS_LANG_MODULE['Create account'] = '创建账户';
$_COS_LANG_MODULE['account'] = '帐户';
$_COS_LANG_MODULE['Users'] = '用户';
$_COS_LANG_MODULE['Logout'] = 'Logout';
$_COS_LANG_MODULE['Email'] = '电子邮件';
$_COS_LANG_MODULE['OpenID'] = 'OpenID的';
$_COS_LANG_MODULE['Facebook'] = 'Facebook的';
$_COS_LANG_MODULE['Github'] = 'Github上';
$_COS_LANG_MODULE['Google'] = '谷歌';
$_COS_LANG_MODULE['Admin'] = '管理员';
