<?php

// Translation of file /home/dennis/www/oscmsdk/modules/account/create/verify.php

$_COS_LANG_MODULE['account_title_verify_account'] = 'Verify Account';
$_COS_LANG_MODULE['account_is_already_verified'] = 'Account already verified';
$_COS_LANG_MODULE['account_has_been_verified'] = 'Account has been verified';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/index.php

$_COS_LANG_MODULE['account_create_index_title'] = 'Create Account';
$_COS_LANG_MODULE['account_create_account_has_been_created'] =
'Account has been created.
You will recieve an email in a short time.
Press a link and you have verified your account!';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/model.create.inc

$_COS_LANG_MODULE['account_error_email_exists'] = 'Email already exists';
$_COS_LANG_MODULE['account_error_password_length'] = 'Password has to be at least 7 chars';
$_COS_LANG_MODULE['account_error_password_mismatch'] = 'Passwords does not match';
$_COS_LANG_MODULE['account_error_invalid_email'] = 'Invalid email';
$_COS_LANG_MODULE['account_error_incorrect_captcha'] = 'Wrong answer to captcha';
$_COS_LANG_MODULE['account_signup_subject'] = 'Create Account confirmation for';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/view.create.inc

$_COS_LANG_MODULE['account_user_create_legend'] = 'Create New Account';
$_COS_LANG_MODULE['account_email_label'] = 'Email';
$_COS_LANG_MODULE['account_password_label'] = 'Password';
$_COS_LANG_MODULE['account_retype_password_label'] = 'Repeat password';
$_COS_LANG_MODULE['account_submit'] = 'Send';
// Translation of file /home/dennis/www/oscmsdk/modules/account/view.account.inc

$_COS_LANG_MODULE['account_welcome_message'] = 'You may log in';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/index.php

$_COS_LANG_MODULE['account_facebook_login'] = 'Facebook Login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/model.facebook.inc

$_COS_LANG_MODULE['account_logged_in_with_email'] = 'Logged in with email';
$_COS_LANG_MODULE['account_logged_in_with_facebook'] = 'Logged in with facebook';
$_COS_LANG_MODULE['account_logout'] = 'Logout';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/index.php

$_COS_LANG_MODULE['account_login_or_logout'] = 'Log in or Log out';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/model.login.inc

$_COS_LANG_MODULE['account_login_wrong_username_password'] = 'Not a correct email or password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/view.login.inc

$_COS_LANG_MODULE['account_form_email'] = 'Email';
$_COS_LANG_MODULE['account_form_password'] = 'Password';
$_COS_LANG_MODULE['account_keep_session'] = 'Keep me logged in for';
$_COS_LANG_MODULE['account_num_days'] = 'days';
$_COS_LANG_MODULE['account_logged_in_with_alternative'] = 'Logged in as';
// Translation of file /home/dennis/www/oscmsdk/modules/account/index.php

$_COS_LANG_MODULE['account_title_index'] = 'Account';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/verify.php

$_COS_LANG_MODULE['account_request_set_new_passwords_title'] = 'Set new password';
$_COS_LANG_MODULE['account_request_new_password_has_been_set'] = 'New password saved';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/view.request_pw.inc

$_COS_LANG_MODULE['account_enter_email_to_recover_lost_password'] = 'Enter email to recreate password';
$_COS_LANG_MODULE['account_request_legend_set_new_password'] = 'Enter new password';
$_COS_LANG_MODULE['account_form_retype_password'] = 'Repeat new password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/index.php

$_COS_LANG_MODULE['account_request_password_title'] = 'Request New Password';
$_COS_LANG_MODULE['account_request_login_info_sent_to'] = 'Login info sent to email. Visit your mailbox
    and follow instructions in order to get a new password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/model.request_pw.inc

$_COS_LANG_MODULE['account_error_no_such_email'] = 'Email does not exists in system';
$_COS_LANG_MODULE['account_request_pw_subject_for_site'] = 'Create new password for site';
$_COS_LANG_MODULE['account_password_length_error'] = 'Password should be at least 7 chars long';
$_COS_LANG_MODULE['account_password_no_match'] = 'Passwords does not match';
$_COS_LANG_MODULE['account_request_no_combination_md5_user'] = 'No such combination between validation code and email. You can only use validation code once';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/views/login.inc

$_COS_LANG_MODULE['account_openid_select_provider'] = 'Select Provider';
$_COS_LANG_MODULE['account_openid_enter_provider'] = 'Login with open ID';
$_COS_LANG_MODULE['account_openid_openid_provider_options'] = 'Options';
$_COS_LANG_MODULE['account_login_open_id_legend'] = 'Log in with open ID';
$_COS_LANG_MODULE['account_open_id_your_open_id_form'] = 'Your ID';
$_COS_LANG_MODULE['account_keep_session'] = 'Keep me logged in for';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/index.php

$_COS_LANG_MODULE['account_openid_login_index'] = 'open ID login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/model.openid.inc

$_COS_LANG_MODULE['account_no_valid_open_id_url'] = 'Not a valid open ID URL';
$_COS_LANG_MODULE['account_openid_valid_login'] = 'Login accepted';
$_COS_LANG_MODULE['account_openid_account_created'] = 'Open ID account created';
$_COS_LANG_MODULE['account_openid_loggedin_message'] = 'Logged ind with open ID';
$_COS_LANG_MODULE['account_openid_invalid_login'] = 'Invalid open ID';
$_COS_LANG_MODULE['account_openid_login_cancelled'] = 'Login cancelled';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/model.admin.inc

$_COS_LANG_MODULE['account_password_error_length'] = 'Password should be at least 7 chars long';
$_COS_LANG_MODULE['account_password_dont_match'] = 'Passwords does not match';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/list.php

// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/delete.php

$_COS_LANG_MODULE['account_delete_account_title'] = 'Delete account';
$_COS_LANG_MODULE['account_has_been_deleted'] = 'Account has been deleted';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/index.php

$_COS_LANG_MODULE['account_index_title'] = 'Account';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/view.admin.inc

$_COS_LANG_MODULE['account_edit_legend'] = 'Edit Account';
$_COS_LANG_MODULE['account_email'] = 'Email';
$_COS_LANG_MODULE['account_password'] = 'Password';
$_COS_LANG_MODULE['account_password_repeat'] = 'Repeat password';
$_COS_LANG_MODULE['account_is_verfied'] = 'Is verified';
$_COS_LANG_MODULE['account_is_admin'] = 'Is Admin';
$_COS_LANG_MODULE['account_is_super'] = 'Is Super';
$_COS_LANG_MODULE['account_form_is_verified'] = 'Is verified';
$_COS_LANG_MODULE['account_form_is_admin'] = 'Is Admin';
$_COS_LANG_MODULE['account_form_is_super'] = 'Is Super';
$_COS_LANG_MODULE['account_update'] = 'Update';
$_COS_LANG_MODULE['account_is_not_admin'] = 'Not admin';
$_COS_LANG_MODULE['account_is_not_super'] = 'Not super';
$_COS_LANG_MODULE['account_is_verified'] = 'Is verified';
$_COS_LANG_MODULE['account_is_not_verified'] = 'Not verified';
$_COS_LANG_MODULE['account_edit'] = 'Edit';
$_COS_LANG_MODULE['account_delete'] = 'Delete';
$_COS_LANG_MODULE['account_delete_account_legend'] = 'Delete account';
$_COS_LANG_MODULE['account_delete_label'] = 'Delete';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/edit.php

$_COS_LANG_MODULE['account_edit_account_title'] = 'Edit Account';
$_COS_LANG_MODULE['account_action_user_updated'] = 'Account updated';

$_COS_LANG_MODULE['account_legend_edit_account'] = 'Edit Account';
$_COS_LANG_MODULE['account_form_username'] = 'Username';
$_COS_LANG_MODULE['account_form_password_retype'] = 'Retype Password';
$_COS_LANG_MODULE['account_login_will_not_be_displayed'] = 'This will not be displayed';
$_COS_LANG_MODULE['account_no_screenname'] = 'No screen name. Set it here: ';
$_COS_LANG_MODULE['account_your_screenname_is'] = 'Your screen name';

$_COS_LANG_MODULE['account_form_openid'] = 'Openid';
$_COS_LANG_MODULE['account_form_submit'] = 'Submit';
$_COS_LANG_MODULE['account_delete_user_legend'] = 'Delete User';

$_COS_LANG_MODULE['account_login_legend'] = 'Login';
