<?php

// Translation of file /home/dennis/www/oscmsdk/modules/account/create/verify.php

$_COS_LANG_MODULE['Verify Account'] = 'Verify Account';
$_COS_LANG_MODULE['Account is already verified'] = 'Account is already verified';
$_COS_LANG_MODULE['Account has been verified'] = 'Account has been verified';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/index.php

$_COS_LANG_MODULE['Create Account'] = 'Create Account';
$_COS_LANG_MODULE['Account: Create notice'] =
'Account has been created.
You will recieve an email in a short time.
Press a link and you have verified your account!';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/model.create.inc

$_COS_LANG_MODULE['Email already exists'] = 'Email already exists';
$_COS_LANG_MODULE['Password has to be at least 7 chars'] = 'Password has to be at least 7 chars';
$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords does not match';
$_COS_LANG_MODULE['Invalid email'] = 'Invalid email';
$_COS_LANG_MODULE['Wrong answer to captcha test'] = 'Wrong answer to captcha test';
$_COS_LANG_MODULE['Confirm account'] = 'Confirm account';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/view.create.inc

$_COS_LANG_MODULE['Create account'] = 'Create account';
$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Repeat password'] = 'Repeat password';
$_COS_LANG_MODULE['Send'] = 'Send';
// Translation of file /home/dennis/www/oscmsdk/modules/account/view.account.inc

$_COS_LANG_MODULE['You can now log in'] = 'You can now log in';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/index.php

$_COS_LANG_MODULE['Facebook Login'] = 'Facebook Login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/model.facebook.inc

$_COS_LANG_MODULE['Logged in with email'] = 'Logged in with email';
$_COS_LANG_MODULE['Logged in with facebook'] = 'Logged in with facebook';
$_COS_LANG_MODULE['account_logout'] = 'Logout';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/index.php

$_COS_LANG_MODULE['Log in or Log out'] = 'Log in or Log out';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/model.login.inc

$_COS_LANG_MODULE['Not a correct email or password'] = 'Not a correct email or password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/view.login.inc

$_COS_LANG_MODULE['Let me stay logged in'] = 'Let me stay logged in';
$_COS_LANG_MODULE['days'] = 'days';
$_COS_LANG_MODULE['Logged in as'] = 'Logged in as';
// Translation of file /home/dennis/www/oscmsdk/modules/account/index.php

$_COS_LANG_MODULE['Account'] = 'Account';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/verify.php

$_COS_LANG_MODULE['Create new password'] = 'Create new password';
$_COS_LANG_MODULE['New password has been saved'] = 'New password has been saved';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/view.request_pw.inc

$_COS_LANG_MODULE['Enter email to recreate password'] = 'Enter email to recreate password';
$_COS_LANG_MODULE['Enter new password'] = 'Enter new password';
$_COS_LANG_MODULE['Repeat new password'] = 'Repeat new password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/index.php

$_COS_LANG_MODULE['Request new password'] = 'Request new password';
$_COS_LANG_MODULE['Visit your mailbox and follow instructions in order to get a new password'] = 'Visit your mailbox and follow instructions in order to get a new password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/model.request_pw.inc

$_COS_LANG_MODULE['Email does not exists in our system'] = 'Email does not exists in our system';
$_COS_LANG_MODULE['Create new password for site'] = 'Create new password for site';

$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords does not match';
$_COS_LANG_MODULE['No such combination between token and email. You can only use the token one time'] = 'No such combination between token and email. You can only use the token one time';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/views/login.inc

$_COS_LANG_MODULE['Select provider'] = 'Select Provider';
$_COS_LANG_MODULE['Log in with openID'] = 'Log in with openID';
$_COS_LANG_MODULE['Choose provider'] = 'Choose provider';

$_COS_LANG_MODULE['Let me stay logged in'] = 'Let me stay logged in';



// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/index.php

$_COS_LANG_MODULE['OpenID login'] = 'OpenID login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/model.openid.inc


$_COS_LANG_MODULE['OpenID login accepted'] = 'OpenID login accepted';

$_COS_LANG_MODULE['Logged ind with openID'] = 'Logged ind with openID';
$_COS_LANG_MODULE['Invalid openID'] = 'Invalid openID';
$_COS_LANG_MODULE['OpenID Login was cancelled'] = 'OpenID Login was cancelled';


// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/view.admin.inc


// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/edit.php

$_COS_LANG_MODULE['Login'] = 'Login';
$_COS_LANG_MODULE['Logout'] = 'Logout';
$_COS_LANG_MODULE['Login using facebook'] = 'Login using facebook';


$_COS_LANG_MODULE['Github login'] = 'Github login';

$_COS_LANG_MODULE['Invalid login. We need a valid OpenID email'] = 'Invalid login. We need a valid OpenID email';
$_COS_LANG_MODULE['Email already exists in system'] = 'Email already exists in system';
$_COS_LANG_MODULE['Account needs to be verified before you may log in'] = 'Account needs to be verified before you may log in';
$_COS_LANG_MODULE['This account has been locked'] = 'This account has been locked';

$_COS_LANG_MODULE['Password needs to be 7 chars'] = 'Password needs to be 7 chars';
$_COS_LANG_MODULE['Admin index'] = 'Admin index';
$_COS_LANG_MODULE['Edit account'] = 'Edit account';
$_COS_LANG_MODULE['Account is verified'] = 'Account is verified';
$_COS_LANG_MODULE['Account is admin'] = 'Account is admin';
$_COS_LANG_MODULE['Account is super'] = 'Account is super';
$_COS_LANG_MODULE['Account is locked'] = 'Account is locked';
$_COS_LANG_MODULE['Update account'] = 'Update account';
$_COS_LANG_MODULE['Delete account'] = 'Delete account';
$_COS_LANG_MODULE['ID'] = 'ID';
$_COS_LANG_MODULE['Account is not admin'] = 'Account is not admin';
$_COS_LANG_MODULE['Account is super user'] = 'Account is super user';
$_COS_LANG_MODULE['Account is not super user'] = 'Account is not super user';
$_COS_LANG_MODULE['Account is not verified'] = 'Account is not verified';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Search accounts'] = 'Search accounts';
$_COS_LANG_MODULE['Search account ID'] = 'Search account ID';
$_COS_LANG_MODULE['Edit account'] = 'Edit account';
$_COS_LANG_MODULE['Account has been updated'] = 'Account has been updated';
$_COS_LANG_MODULE['Found the following accounts'] = 'Found the following accounts';
$_COS_LANG_MODULE['I could not find any matching results'] = 'I could not find any matching results';
$_COS_LANG_MODULE['Search for users'] = 'Search for users';
$_COS_LANG_MODULE['Delete account'] = 'Delete account';
$_COS_LANG_MODULE['Account has been deleted'] = 'Account has been deleted';
$_COS_LANG_MODULE['That is not a valid email'] = 'That is not a valid email';
$_COS_LANG_MODULE['Incorrect answer to captcha test'] = 'Incorrect answer to captcha test';
$_COS_LANG_MODULE['Password needs to be 7 chars'] = 'Password needs to be 7 chars';
$_COS_LANG_MODULE['Emails does not match'] = 'Emails does not match';
$_COS_LANG_MODULE['Account created'] = 'Account created';
$_COS_LANG_MODULE['Wrong validation key on account creation'] = 'Wrong validation key on account creation';
$_COS_LANG_MODULE['Confirm account creation'] = 'Confirm account creation';
$_COS_LANG_MODULE['Hi'] = 'Hi';
$_COS_LANG_MODULE['You have connected with'] = 'You have connected with';
$_COS_LANG_MODULE['because you have lost
your password'] = 'because you have lost
your password';
$_COS_LANG_MODULE['In order to create a new password just press the
following link or paste it into your browsers URL line'] = 'In order to create a new password just press the
following link or paste it into your browsers URL line';
$_COS_LANG_MODULE['If you have not requested a new password then you can just delete
this message'] = 'If you have not requested a new password then you can just delete
this message';
