<?php


// Translation of file /modules/account/module.php

$_COS_LANG_MODULE['Account needs to be verified before you may log in'] = 'Account needs to be verified before you may log in';
$_COS_LANG_MODULE['This account has been locked'] = 'This account has been locked';

// Translation of file /modules/account/login/module.php

$_COS_LANG_MODULE['Log in or Log out'] = 'Log in or Log out';
$_COS_LANG_MODULE['Not a correct email or password'] = 'Not a correct email or password';

// Translation of file /modules/account/login/create.php

$_COS_LANG_MODULE['Create Account'] = 'Create Account';
$_COS_LANG_MODULE['Account: Create notice'] = 'Account has been created. You will recieve an email in a short time. Press a link and you have verified your account!';

// Translation of file /modules/account/login/views.php

$_COS_LANG_MODULE['Create account'] = 'Create account';
$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Repeat password'] = 'Repeat password';
$_COS_LANG_MODULE['Send'] = 'Send';
$_COS_LANG_MODULE['Login'] = 'Login';
$_COS_LANG_MODULE['Let me stay logged in'] = 'Let me stay logged in';
$_COS_LANG_MODULE['days'] = 'days';

// Translation of file /modules/account/api/module.php

$_COS_LANG_MODULE['User with ID <span class="notranslate">{ID}</span> has been locked!'] = 'User with ID <span class="notranslate">{ID}</span> has been locked!';
$_COS_LANG_MODULE['Not sufficient privileges. Super user is required'] = 'Not sufficient privileges. Super user is required';

// Translation of file /modules/account/views/mails/signup_message.inc

$_COS_LANG_MODULE['Hi'] = 'Hi';
$_COS_LANG_MODULE['You have connected with {SITE_NAME} and requested an account'] = 'You have connected with {SITE_NAME} and requested an account';
$_COS_LANG_MODULE['In order to activate your account, you just have to press the following link or copy and paste into your browsers URL line'] = 'In order to activate your account, you just have to press the following link or copy and paste into your browsers URL line';
$_COS_LANG_MODULE['Kind Regards'] = 'Kind Regards';

// Translation of file /modules/account/views/mails/request_password.inc

$_COS_LANG_MODULE['You have connected with {SITE_NAME} because you have lost your password'] = 'You have connected with {SITE_NAME} because you have lost your password';
$_COS_LANG_MODULE['In order to create a new password just press the following link or paste it into your browsers URL line'] = 'In order to create a new password just press the following link or paste it into your browsers URL line';
$_COS_LANG_MODULE['If you have not requested a new password then you can just delete this message'] = 'If you have not requested a new password then you can just delete this message';

// Translation of file /modules/account/facebook/module.php

$_COS_LANG_MODULE['Email already exists in system'] = 'Email already exists in system';

// Translation of file /modules/account/facebook/views.php

$_COS_LANG_MODULE['Login using facebook'] = 'Login using facebook';
$_COS_LANG_MODULE['Logout'] = 'Logout';

// Translation of file /modules/account/facebook/index.php

$_COS_LANG_MODULE['Facebook Login'] = 'Facebook Login';

// Translation of file /modules/account/admin/module.php

$_COS_LANG_MODULE['Password needs to be 7 chars'] = 'Password needs to be 7 chars';
$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords does not match';

// Translation of file /modules/account/admin/delete.php

$_COS_LANG_MODULE['Delete account'] = 'Delete account';
$_COS_LANG_MODULE['Account has been deleted'] = 'Account has been deleted';

// Translation of file /modules/account/admin/edit.php

$_COS_LANG_MODULE['Edit account'] = 'Edit account';
$_COS_LANG_MODULE['Account has been updated'] = 'Account has been updated';

// Translation of file /modules/account/admin/views.php

$_COS_LANG_MODULE['Account is verified'] = 'Account is verified';
$_COS_LANG_MODULE['Account is super'] = 'Account is super';
$_COS_LANG_MODULE['Account is admin'] = 'Account is admin';
$_COS_LANG_MODULE['Account is locked'] = 'Account is locked';
$_COS_LANG_MODULE['Update account'] = 'Update account';
$_COS_LANG_MODULE['ID'] = 'ID';
$_COS_LANG_MODULE['Account is not admin'] = 'Account is not admin';
$_COS_LANG_MODULE['Account is super user'] = 'Account is super user';
$_COS_LANG_MODULE['Account is not super user'] = 'Account is not super user';
$_COS_LANG_MODULE['Account is not verified'] = 'Account is not verified';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Search accounts'] = 'Search accounts';
$_COS_LANG_MODULE['Search account ID'] = 'Search account ID';
$_COS_LANG_MODULE['Search'] = 'Search';

// Translation of file /modules/account/admin/list.php

$_COS_LANG_MODULE['Found the following accounts'] = 'Found the following accounts';
$_COS_LANG_MODULE['I could not find any matching results'] = 'I could not find any matching results';
$_COS_LANG_MODULE['Search for users'] = 'Search for users';

// Translation of file /modules/account/admin/index.php

$_COS_LANG_MODULE['Admin index'] = 'Admin index';

// Translation of file /modules/account/github/module.php

$_COS_LANG_MODULE['Github login'] = 'Github login';

// Translation of file /modules/account/github/index.php


// Translation of file /modules/account/views.php

$_COS_LANG_MODULE['By registering, you agree to the <a href="/account/terms/privacy">privacy policy</a> and <a href="/account/terms/service">terms of service</a>.'] = 'By registering, you agree to the <a href="/account/terms/privacy">privacy policy</a> and <a href="/account/terms/service">terms of service</a>.';

// Translation of file /modules/account/requestpw/module.php

$_COS_LANG_MODULE['Wrong answer to captcha test'] = 'Wrong answer to captcha test';
$_COS_LANG_MODULE['Email does not exists in our system'] = 'Email does not exists in our system';
$_COS_LANG_MODULE['Create new password for site'] = 'Create new password for site';
$_COS_LANG_MODULE['Password has to be at least 7 chars'] = 'Password has to be at least 7 chars';
$_COS_LANG_MODULE['No such combination between token and email. You can only use the token one time'] = 'No such combination between token and email. You can only use the token one time';
$_COS_LANG_MODULE['Request new password'] = 'Request new password';
$_COS_LANG_MODULE['Visit your mailbox and follow instructions in order to get a new password'] = 'Visit your mailbox and follow instructions in order to get a new password';
$_COS_LANG_MODULE['We could not not send you an email. Please try again later'] = 'We could not not send you an email. Please try again later';

// Translation of file /modules/account/requestpw/views.php

$_COS_LANG_MODULE['Enter new password'] = 'Enter new password';
$_COS_LANG_MODULE['Repeat new password'] = 'Repeat new password';

// Translation of file /modules/account/requestpw/verify.php

$_COS_LANG_MODULE['Create new password'] = 'Create new password';
$_COS_LANG_MODULE['New password has been saved'] = 'New password has been saved';

// Translation of file /modules/account/changeemail/model.changeemail.inc

$_COS_LANG_MODULE['Email already exists'] = 'Email already exists';
$_COS_LANG_MODULE['Confirm account creation'] = 'Confirm account creation';

// Translation of file /modules/account/lightopenid/module.php

$_COS_LANG_MODULE['OpenID Login was cancelled'] = 'OpenID Login was cancelled';
$_COS_LANG_MODULE['OpenID login accepted'] = 'OpenID login accepted';
$_COS_LANG_MODULE['Invalid openID'] = 'Invalid openID';
$_COS_LANG_MODULE['Logged ind with openID'] = 'Logged ind with openID';
$_COS_LANG_MODULE['Invalid login. We need a valid OpenID email'] = 'Invalid login. We need a valid OpenID email';

// Translation of file /modules/account/lightopenid/index.php

$_COS_LANG_MODULE['OpenID login'] = 'OpenID login';

// Translation of file /modules/account/index.php

$_COS_LANG_MODULE['Account'] = 'Account';

// Translation of file /modules/account/create/module.php

$_COS_LANG_MODULE['That is not a valid email'] = 'That is not a valid email';
$_COS_LANG_MODULE['Incorrect answer to captcha test'] = 'Incorrect answer to captcha test';
$_COS_LANG_MODULE['Emails does not match'] = 'Emails does not match';
$_COS_LANG_MODULE['Account created'] = 'Account created';
$_COS_LANG_MODULE['Wrong validation key on account creation'] = 'Wrong validation key on account creation';

// Translation of file /modules/account/create/verify.php

$_COS_LANG_MODULE['Verify Account'] = 'Verify Account';
$_COS_LANG_MODULE['Account is already verified'] = 'Account is already verified';
$_COS_LANG_MODULE['Account has been verified'] = 'Account has been verified';
