<?php


// Translation of file /modules/account/install.inc

$_COS_LANG_MODULE['account'] = 'Account';

// Translation of file /modules/account/login/menu.inc

$_COS_LANG_MODULE['Lost password'] = 'Lost password';
$_COS_LANG_MODULE['Create account'] = 'Create account';

// Translation of file /modules/account/admin/menu.inc

$_COS_LANG_MODULE['Search for users'] = 'Search for users';

// Translation of file /modules/account/menu.inc

$_COS_LANG_MODULE['Email login'] = 'Email login';
$_COS_LANG_MODULE['OpenID'] = 'OpenID';
$_COS_LANG_MODULE['Facebook'] = 'Facebook';
$_COS_LANG_MODULE['Github'] = 'Github';
$_COS_LANG_MODULE['Admin'] = 'Admin';
