<?php

// Translation of menu file /home/dennis/www/oscmsdk/modules/account/menu.inc

$_COS_LANG_MODULE['account_login_with_email'] = 'Email Login';
$_COS_LANG_MODULE['account_create_email_account'] = 'Create Account';
$_COS_LANG_MODULE['account_request_password'] = 'Lost password?';
$_COS_LANG_MODULE['account_use_open_id'] = 'OpenID';
$_COS_LANG_MODULE['account_login_facebook'] = 'Facebook';
$_COS_LANG_MODULE['account_admin'] = 'Admin';
// Translation of menu file /home/dennis/www/oscmsdk/modules/account/admin/menu.inc

$_COS_LANG_MODULE['account_list_users'] = 'Show accounts';
$_COS_LANG_MODULE['Account'] = 'Account';


