<?php

$_COS_LANG_MODULE['account'] = 'Konto';
$_COS_LANG_MODULE['Lost password'] = 'Mistet passordet ditt?';
$_COS_LANG_MODULE['Create account'] = 'Registrer deg';
$_COS_LANG_MODULE['Search for users'] = 'Søk etter brukere';
$_COS_LANG_MODULE['Email login'] = 'Logg inn med e-post';
$_COS_LANG_MODULE['OpenID'] = 'OpenID';
$_COS_LANG_MODULE['Facebook'] = 'Facebook';
$_COS_LANG_MODULE['Github'] = 'Github';
$_COS_LANG_MODULE['Admin'] = 'Admin';
