<?php

$db_config = array (
    array ('name' => 'account_db_text', 
           'description' => lang::translate('account_test_description'),
           'type' => 'text', 
           'value' => 'tester',
           'auth' => 'super'),
    array ('name' => 'account_db_textarea', 
           'description' => lang::translate('account_textarea_description'),
           'type' => 'textarea', 
           'value' => 'tester area',
           'auth' => 'super'),
);