<?php

$_COS_LANG_MODULE['account'] = 'Konto';
$_COS_LANG_MODULE['Lost password'] = 'Passwort vergessen';
$_COS_LANG_MODULE['Create account'] = 'Konto erstellen';
$_COS_LANG_MODULE['Search for users'] = 'Suche nach Benutzern';
$_COS_LANG_MODULE['Email'] = 'E-Mail';
$_COS_LANG_MODULE['OpenID'] = 'OpenID';
$_COS_LANG_MODULE['Facebook'] = 'Facebook';
$_COS_LANG_MODULE['Github'] = 'Github';
$_COS_LANG_MODULE['Admin'] = 'Admin';
