<?php

// Translation of file /home/dennis/www/oscmsdk/modules/account/create/verify.php

$_COS_LANG_MODULE['Verify Account'] = 'Verificer Konto';
$_COS_LANG_MODULE['Account is already verified'] = 'Konto er allerede verificeret';
$_COS_LANG_MODULE['Account has been verified'] = 'Konto er blevet verificeret. Du kan nu <a href="/account/login/index">logge ind</a>';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/index.php

$_COS_LANG_MODULE['Create Account'] = 'Opret konto';
$_COS_LANG_MODULE['Account: Create notice'] = 'Konto er blevet oprettet. 
Du vil modtage en email i løbet af kort tid.     
Tryk et link i denne mail og du er verificeret.';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/model.create.inc

$_COS_LANG_MODULE['Email already exists'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['Password has to be at least 7 chars'] = 'Password skal mindst være 7 karaktere langt';
$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords stemmer ikke overens';
$_COS_LANG_MODULE['Invalid email'] = 'Ugyldig email';
$_COS_LANG_MODULE['Wrong answer to captcha test'] = 'Ikke et korrekt svar til captcha';
$_COS_LANG_MODULE['Confirm account'] = 'Oprettelse af konto på';
// Translation of file /home/dennis/www/oscmsdk/modules/account/create/view.create.inc

$_COS_LANG_MODULE['Create account'] = 'Opret konto';
$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Repeat password'] = 'Gentag password';
$_COS_LANG_MODULE['account_submit'] = 'Send';
// Translation of file /home/dennis/www/oscmsdk/modules/account/view.account.inc

$_COS_LANG_MODULE['You can now log in'] = 'Velkommen';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/index.php

$_COS_LANG_MODULE['Facebook Login'] = 'Facebook login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/facebook/model.facebook.inc

$_COS_LANG_MODULE['Logged in with email'] = 'Logget ind med email';
$_COS_LANG_MODULE['Logged in with facebook'] = 'Logget ind med facebook';
$_COS_LANG_MODULE['account_logout'] = 'Log ud';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/index.php

$_COS_LANG_MODULE['Log in or Log out'] = 'Log ind eller ud';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/model.login.inc

$_COS_LANG_MODULE['Not a correct email or password'] = 'Enten forkert password eller email';
// Translation of file /home/dennis/www/oscmsdk/modules/account/login/view.login.inc

$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Let me stay logged in'] = 'Forbliv logget ind';
$_COS_LANG_MODULE['days'] = 'dage';
$_COS_LANG_MODULE['Logged in as'] = 'Logget in med alternativ til email';
// Translation of file /home/dennis/www/oscmsdk/modules/account/index.php

$_COS_LANG_MODULE['Account'] = 'Konto';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/verify.php

$_COS_LANG_MODULE['Create new password'] = 'Nyt password';
$_COS_LANG_MODULE['New password has been saved'] = 'Nyt password er blevet gemt';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/view.request_pw.inc

$_COS_LANG_MODULE['Enter email to recreate password'] = 'Indtast din email for at genskabe password';
$_COS_LANG_MODULE['Enter new password'] = 'Indtast nyt password';
$_COS_LANG_MODULE['Repeat new password'] = 'Gentag password';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/index.php

$_COS_LANG_MODULE['Request new password'] = 'Opret nyt password';
$_COS_LANG_MODULE['Visit your mailbox and follow instructions in order to get a new password'] = 'Check din email. Heri er der instruktioner til at 
    skabe et nyt password.';
// Translation of file /home/dennis/www/oscmsdk/modules/account/request_pw/model.request_pw.inc

$_COS_LANG_MODULE['Email does not exists in our system'] = 'Ingen sådan email i systemet';
$_COS_LANG_MODULE['Create new password for site'] = 'Genskabelse af password';
$_COS_LANG_MODULE['Password has to be at least 7 chars'] = 'Password skal mindst være syv karakterer langt';
$_COS_LANG_MODULE['Passwords does not match'] = 'De to password er ikke ens';
$_COS_LANG_MODULE['No such combination between token and email. You can only use the token one time'] = 'Ingen sådan kombination mellem bruger id og validerings kode';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/views/login.inc

$_COS_LANG_MODULE['Select provider'] = 'Vælg udbyder';
$_COS_LANG_MODULE['Log in with openID'] = 'Log ind med open ID';
$_COS_LANG_MODULE['Choose provider'] = 'Options';
$_COS_LANG_MODULE['Log in with openID'] = 'Log ind med open ID';
$_COS_LANG_MODULE['account_open_id_your_open_id_form'] = 'Dit open ID';
$_COS_LANG_MODULE['Let me stay logged in'] = 'Forbliv logget ind';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/index.php

$_COS_LANG_MODULE['OpenID login'] = 'open ID login';
// Translation of file /home/dennis/www/oscmsdk/modules/account/openid/model.openid.inc

$_COS_LANG_MODULE['account_no_valid_open_id_url'] = 'Ikke en gyldig open ID URL';
$_COS_LANG_MODULE['OpenID login accepted'] = 'Gyldigt login';
$_COS_LANG_MODULE['account_openid_account_created'] = 'Open ID konto oprettet';
$_COS_LANG_MODULE['Logged ind with openID'] = 'Logget ind med open ID';
$_COS_LANG_MODULE['Invalid openID'] = 'Ugyldigt login';
$_COS_LANG_MODULE['OpenID Login was cancelled'] = 'Login afbrudt';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/model.admin.inc

$_COS_LANG_MODULE['account_password_error_length'] = 'Password skal mindst være 7 karakterer langt';
$_COS_LANG_MODULE['account_password_dont_match'] = 'Passwords matcher ikke';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/list.php

// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/delete.php

$_COS_LANG_MODULE['account_delete_account_title'] = 'Slet Konto';
$_COS_LANG_MODULE['account_has_been_deleted'] = 'Konto er blevet slettet';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/index.php

$_COS_LANG_MODULE['account_index_title'] = 'Konto';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/view.admin.inc

$_COS_LANG_MODULE['account_edit_legend'] = 'Ret konto';
$_COS_LANG_MODULE['account_email'] = 'Email';
$_COS_LANG_MODULE['account_password'] = 'Password';
$_COS_LANG_MODULE['account_password_repeat'] = 'Gentag password';
$_COS_LANG_MODULE['account_is_verfied'] = 'Verificeret';
$_COS_LANG_MODULE['account_is_admin'] = 'Admin';
$_COS_LANG_MODULE['account_is_super'] = 'Super';
$_COS_LANG_MODULE['account_form_is_verified'] = 'Er verificeret';
$_COS_LANG_MODULE['account_form_is_admin'] = 'Admin';
$_COS_LANG_MODULE['account_form_is_super'] = 'Super';
$_COS_LANG_MODULE['account_update'] = 'Opdater';
$_COS_LANG_MODULE['account_is_not_admin'] = 'Ikke admin';
$_COS_LANG_MODULE['account_is_not_super'] = 'ikke super';
$_COS_LANG_MODULE['account_is_verified'] = 'Er verificeret';
$_COS_LANG_MODULE['account_is_not_verified'] = 'Ikke verificeret';
$_COS_LANG_MODULE['account_edit'] = 'Ret';
$_COS_LANG_MODULE['account_delete'] = 'Slet';
$_COS_LANG_MODULE['account_delete_account_legend'] = 'Slet konto';
$_COS_LANG_MODULE['account_delete_label'] = 'Slet';
// Translation of file /home/dennis/www/oscmsdk/modules/account/admin/edit.php

$_COS_LANG_MODULE['account_edit_account_title'] = 'Ret konto';
$_COS_LANG_MODULE['account_action_user_updated'] = 'Konto opdateret';

$_COS_LANG_MODULE['account_login_will_not_be_displayed'] = 'Vil ikke blive vist';
$_COS_LANG_MODULE['account_no_screenname'] = 'Intet skærm navn';
$_COS_LANG_MODULE['account_your_screenname_is'] = 'Dit skærm navn er';
$_COS_LANG_MODULE['account_legend_edit_account'] = 'Ret konto';
$_COS_LANG_MODULE['account_form_openid'] = 'Open ID';
$_COS_LANG_MODULE['account_form_username'] = 'Brugernavn';
$_COS_LANG_MODULE['Password_retype'] = 'Gentag password';
$_COS_LANG_MODULE['account_form_submit'] = 'Send';
$_COS_LANG_MODULE['account_delete_user_legend'] = 'Slet Bruger';

$_COS_LANG_MODULE['Login'] = 'Log ind';

$_COS_LANG_MODULE['account_openid_login_failed'] = 'OpenID login mislykkedes. Check openID URL';
$_COS_LANG_MODULE['account_logged_in_with_open_id'] = 'Logget ind med OpenID';

$_COS_LANG_MODULE['account_wrong_validation_combination'] = 'Forkert kombination mellem bruger og validerings nøgle';

$_COS_LANG_MODULE['Logout'] = 'Log ud';
$_COS_LANG_MODULE['Login using facebook'] = 'Log ind';
$_COS_LANG_MODULE['account_error_email_does_not_match'] = 'Emails matcher ikke';

$_COS_LANG_MODULE['account: admin: search legend'] = 'Søg efter bruger';
$_COS_LANG_MODULE['account: admin: search user id'] = 'Søg efter ID eller email';
$_COS_LANG_MODULE['account: admin: found results'] = 'Fandt følgende bruger: ';
$_COS_LANG_MODULE['account: admin: found no results'] = 'Ingen resultat';


$_COS_LANG_MODULE['Github login'] = 'Github login';

$_COS_LANG_MODULE['Email already exists in system'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['Invalid login. We need a valid OpenID email'] = 'Ikke en gyldig email';
$_COS_LANG_MODULE['Email already exists in system'] = 'Email eksisterer allerede';
$_COS_LANG_MODULE['account: is locked'] = 'Konto er låst';
$_COS_LANG_MODULE['Account needs to be verified before you may log in'] = 'Konto skal verificeres før du kan logge ind';
$_COS_LANG_MODULE['This account has been locked'] = 'Konto er låst';
$_COS_LANG_MODULE['account: error: email exists'] = 'Email eksisterer allerede';

$_COS_LANG_MODULE['account: ID'] = 'ID';
$_COS_LANG_MODULE['account: email'] = 'Email';


$_COS_LANG_MODULE['Email already exists in system'] = 'Email eksisterer allerede';
