<?php

$_COS_LANG_MODULE['Email login'] = 'Email Login';
$_COS_LANG_MODULE['Create account'] = 'Create account';
$_COS_LANG_MODULE['Lost password'] = 'Lost password?';
$_COS_LANG_MODULE['OpenID'] = 'OpenID';
$_COS_LANG_MODULE['Facebook'] = 'Facebook';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['Account'] = 'Account';
$_COS_LANG_MODULE['Github'] = 'Github';
$_COS_LANG_MODULE['Search for users'] = 'Search for users';
