<?php

/**
 * @package    account
 */

/**
 * function for creating a login form
 */

class accountLoginView {

    /**
     *
     * @var string  string holding extensions html to add to login.
     */
    /*
    public static $accountLoginHTML = '';
     */
    /**
     * method for displayng default login box
     */
    /*
    public static function login (){
        echo templateView::get('account', 'account_login_email');
        if (isset(self::$accountLoginHTML)){
            echo self::$accountLoginHTML;
        }
    }*/

   /**
    * method for creating a logout link
    */
    /*
    public static function logout(){
        accountLogin::setId();
        $row = accountLogin::getUser();  
        echo user::getLogoutHTML($row);       
    }*/
}
