<?php

/**
 * translation file
 * 
 * @package    account
 */
$_COS_LANG_MODULE['Create Account'] = 'Create Account';

# account module
$_COS_LANG_MODULE['Edit Account'] = 'Edit Account';
$_COS_LANG_MODULE['List Users'] = 'List Users';
$_COS_LANG_MODULE['Welcome to the account module'] =  "Welcome to the account module";


$_COS_LANG_MODULE['Request Password'] = 'Request Password';
$_COS_LANG_MODULE['Enter password'] = 'Enter password';
$_COS_LANG_MODULE['Username'] = 'Username';
$_COS_LANG_MODULE['Password'] = 'Password';
$_COS_LANG_MODULE['Retype Password'] = 'Retype Password';
$_COS_LANG_MODULE['Get an user account by filling out the following form'] = 'Get an user account by filling out the following form';

$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['Passwords does not match'] = 'Passwords does not match';
$_COS_LANG_MODULE['Username exists. Pick another'] = 'Username exists. Pick another';
$_COS_LANG_MODULE['Not a valid email'] = 'Not a valid email';
$_COS_LANG_MODULE['You are logged in'] = 'You are logged in';
$_COS_LANG_MODULE['Logout'] = 'Logout';
$_COS_LANG_MODULE['Login'] = 'Login';
$_COS_LANG_MODULE['Login or logout'] = 'Login or logout';
$_COS_LANG_MODULE['Wrong email or password'] = 'Wrong email or password';

$_COS_LANG_MODULE['Error'] = 'Error';
$_COS_LANG_MODULE['Username can only contain alphabetic chars and number and . and _'] = 'Username can only contain alphabetic chars and number and . and _';
$_COS_LANG_MODULE['Username should be at least 5 chars long'] = 'Username should be at least 5 chars long';
$_COS_LANG_MODULE['Password should be at least 5 chars long'] = 'Password should be at least 5 chars long';
$_COS_LANG_MODULE['Login info sent to'] = 'Login info sent to';
$_COS_LANG_MODULE['No such email'] = 'No such email';
$_COS_LANG_MODULE['Enter email to require lost password'] = 'Enter email to require lost password';
$_COS_LANG_MODULE['Email already exists.'] = 'Email already exists.';
$_COS_LANG_MODULE['New account has been created'] = 'New account has been created. In order to activate you new account, you need to visit your mailbox and follow the instructions';
$_COS_LANG_MODULE['Set New Password'] = 'Set New Password';
$_COS_LANG_MODULE['New passwords has been set'] = 'New passwords has been set';
$_COS_LANG_MODULE['No such combination between user and validation key'] = 'No such combination between user and validation key';
$_COS_LANG_MODULE['Set your new password'] = 'Set your new password';

$_COS_LANG_MODULE['Not Admin'] = 'Not Admin';
$_COS_LANG_MODULE['Verified'] = 'Verified';
$_COS_LANG_MODULE['Not Verified'] = 'Not Verified';
$_COS_LANG_MODULE['List Users'] = 'List Users';
$_COS_LANG_MODULE['Edit User'] = 'Edit User';
$_COS_LANG_MODULE['User Updated'] = 'User Updated';
$_COS_LANG_MODULE['Edit User Account'] = 'Edit User Account';
$_COS_LANG_MODULE['Is Admin'] = 'Is Admin';
$_COS_LANG_MODULE['Delete User'] = 'Delete User';
$_COS_LANG_MODULE['User Deleted'] = 'User Deleted';

#signup messages
$_COS_LANG_MODULE['signup'] = "Welcome !username!\n\n";
$_COS_LANG_MODULE['signup'].= "You have signed up for an user account on !site_name!\n";
$_COS_LANG_MODULE['signup'].= "In order to finish your registration you have to press the\n";
$_COS_LANG_MODULE['signup'].= "following link or paste it into the adresse line of the browser\n\n";
$_COS_LANG_MODULE['signup'].= "!verify_key!\n\n";
$_COS_LANG_MODULE['signup_subject'] = "Account verification for !site_name!";


$_COS_LANG_MODULE['request_pw'] = "Hi !username!\n\n";
$_COS_LANG_MODULE['request_pw'].= "You have notified us at !site_name! because you have lost\n";
$_COS_LANG_MODULE['request_pw'].= "Your password. In order to create a new password visit the";
$_COS_LANG_MODULE['request_pw'].= "following link or paste it into the adresse line of the browser\n\n";
$_COS_LANG_MODULE['request_pw'].= "!verify_key!\n\n";
$_COS_LANG_MODULE['request_pw_subject'] = "Recover lost password for !site_name!";

$_COS_LANG_MODULE['Incorrect answer to captcha test'] = 'Incorrect answer to captcha test';
$_COS_LANG_MODULE['Account has been verified. You may log in'] = 'Account has been verified. You may log in';

$_COS_LANG_MODULE['Is Super'] = 'Is Super';

$_COS_LANG_MODULE['use_open_id'] = 'Login with OpenID';
$_COS_LANG_MODULE['login_open_id'] = 'Or Enter your full OpenID';
$_COS_LANG_MODULE['your_open_id'] = 'Your open ID';

$_COS_LANG_MODULE['openid_loggedin_message'] = 'You are successful logged in!';
$_COS_LANG_MODULE['openid_user_logged_in'] = 'You are logged in with openID';



$_COS_LANG_MODULE['list_openids'] = 'Show users with openID';

$_COS_LANG_MODULE['Super'] = 'Super';
$_COS_LANG_MODULE['Not Super'] = 'Not Super';

$_COS_LANG_MODULE['openid'] = 'openID';
$_COS_LANG_MODULE['logged_in_with_email'] =  'Logged in with email';

$_COS_LANG_MODULE['logged_in_with_openid'] = 'Your are logged in with openID';

$_COS_LANG_MODULE['no_valid_open_id_url'] = 'Enter a valid openID URL';
$_COS_LANG_MODULE['openid_login_failed'] = 'openID login failed';

$_COS_LANG_MODULE['keep_session'] = 'Stay logged in next';

$_COS_LANG_MODULE['days'] = 'days';



$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Submit'] = 'Submit';


$_COS_LANG_MODULE['Verify Account'] = 'Verify Account';


$_COS_LANG_MODULE['Submit'] = 'Submit';



$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';






$_COS_LANG_MODULE['Account Admin'] = 'Account Admin';


$_COS_LANG_MODULE['Submit'] = 'Submit';

$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Delete'] = 'Delete';

$_COS_LANG_MODULE['openid_valid_login'] = 'Valid openID login';
$_COS_LANG_MODULE['openid_account_created'] = 'Account connected to openID created';
$_COS_LANG_MODULE['openid_invalid_login'] = 'Not a valid openID login';
$_COS_LANG_MODULE['openid_login_cancelled'] = 'OpenID login cancelled';


$_COS_LANG_MODULE['Submit'] = 'Submit';


$_COS_LANG_MODULE['logged_in_with_facebook'] = 'Logged in with facebook account';
$_COS_LANG_MODULE['account_urlid'] = 'URL ID';
$_COS_LANG_MODULE['logged_in_with_alternative'] = 'Logged in with';

$_COS_LANG_MODULE['account_openid_select_provider'] = 'Select provider';
$_COS_LANG_MODULE['account_openid_select_openid_provider'] = 'account_openid_select_openid_provider';
$_COS_LANG_MODULE['Search'] = 'Search';

$_COS_LANG_MODULE['Select Provider'] = 'Select Provider';
