<?php


/**
 * translation file
 *
 * @package    account
 */
$_COS_LANG_MODULE['Account'] = 'Account';
$_COS_LANG_MODULE['account'] = 'Account';
$_COS_LANG_MODULE['account_create_email_account'] = 'Create Account With Email';
$_COS_LANG_MODULE['account_request_password'] = 'Request Password';
$_COS_LANG_MODULE['account_use_open_id'] = 'Login with OpenID';
$_COS_LANG_MODULE['account_admin'] = 'Admin';
$_COS_LANG_MODULE['account_list_users'] = 'List Users';
$_COS_LANG_MODULE['account_list_openids'] = 'List OpenIDs';


$_COS_LANG_MODULE['account_login_with_email'] = 'Login with Email';

$_COS_LANG_MODULE['account_login_facebook'] = 'Facebook login';


