<?php

$_COS_LANG_MODULE['account'] = 'Tili';
$_COS_LANG_MODULE['Lost password'] = 'Hukassa?';
$_COS_LANG_MODULE['Create account'] = 'Luo tili';
$_COS_LANG_MODULE['Search for users'] = 'Etsi käyttäjää';
$_COS_LANG_MODULE['Email login'] = 'Kirjautuaksesi';
$_COS_LANG_MODULE['OpenID'] = 'OpenID';
$_COS_LANG_MODULE['Facebook'] = 'Facebook';
$_COS_LANG_MODULE['Github'] = 'Github';
$_COS_LANG_MODULE['Admin'] = 'Admin';
