<?php

template::setInlineCss(config::getModulePath('account') . "/assets/account.css");

class viewAccountAdmin {

   /**
    * function for updating a user
    *
    * @param array row to use when updating a user
    */
    function updateEmailUser ($values){

        if (!isset($_POST['submit'])){
            $values['password'] = '';
            $values['password2'] = '';
        } 

        html::$autoLoadTrigger = 'submit';
        html::init($values);
        html::formStart('account_form');
        html::legend(lang::translate('account_edit_legend'));
        html::label('email', lang::translate('account_email') );
        html::text('email');
        html::label('password', lang::translate('account_password') );
        html::password('password');
        html::label('password2', lang::translate('account_password_repeat') );
        html::password('password2');
        html::label('verified', lang::translate('account_is_verfied') );
        html::checkbox ('verified');
        html::label('admin', lang::translate('account_is_admin') );
        html::checkbox ('admin');
        html::label('super', lang::translate('account_is_super') );
        html::checkbox ('super');
        html::submit('submit', lang::translate('account_update'));
        html::formEnd();
        echo html::getStr();

   }

    public function updateUrlUser ($values){

        html::$autoLoadTrigger = 'submit';
        html::init($values);
        html::formStart('account_form');
        html::legend(lang::translate('account_edit_legend'));
        html::label('verified', lang::translate('account_form_is_verified') );
        html::checkbox ('verified');
        html::label('admin', lang::translate('account_form_is_admin') );
        html::checkbox ('admin');
        html::label('super', lang::translate('account_form_is_super') );
        html::checkbox ('super');
        html::submit('submit', lang::translate('account_update'));
        html::formEnd();
        echo html::getStr();
    }
   
    /**
     * function for view a delete user form
     *
     * @param array row with user
     */
    public function delete ($values){
        html::formStart('account_form');
        html::legend(lang::translate('account_delete_account_legend'));
        html::submit('submit', lang::translate('account_delete'));
        html::formEnd();
        echo html::getStr();
    }
    
    public function listUsers ($users) {

        foreach ($users as $k => $user) {
            echo self::listUser( $user);
        }
    }
    
    public function listUser ($v) {
        $date = time::getDateString($v['created']);

        echo "<div class=\"account_admin_user\">\n";
        echo user::getProfile($v, $date, array ('user_id'));


        if ($v['admin']) {
            echo lang::translate('account_is_admin');
        } else {
            echo lang::translate('account_is_not_admin');
        }
        echo "<br />\n";

        if ($v['super']) {
            echo lang::translate('account_is_super');
        } else {
            echo lang::translate('account_is_not_super');
        }
        echo "<br />\n";

        if ($v['verified']) {
            echo lang::translate('account_is_verified');
        } else {
            echo lang::translate('account_is_not_verified');
        }
        echo "<br />\n";

        echo html::createLink("/account/admin/edit/$v[id]", lang::translate('account_edit'));
        echo MENU_SUB_SEPARATOR;
        echo html::createLink("/account/admin/delete/$v[id]", lang::translate('account_delete'));
        echo "<br />\n";
        echo "<br />\n";
        echo "</div>\n";
    }
    
    public function searchForm () {
        $f = new html ();
        $f->formStart('form_search', 'get');
        $f->legend(lang::translate('account: admin: search legend'));
        $f->init(null, 'submit');
        $f->label('id', lang::translate('account: admin: search user id'));
        $f->text('id');
        $f->submit('submit', lang::system('submit'));
        $f->formEnd();
        echo $f->getStr();
                
    }
}
