<?php

class accountRequestpwView {
    public static function formVerify () {
        $field_size = array ('size' => '30');
        html::$autoLoadTrigger = 'submit';
        html::init($_POST);
        html::formStart('account_set_new_password');
        html::legend(lang::translate('account_request_legend_set_new_password'));
        html::label('password1', lang::translate('account_form_password'));
        html::password('password1',  null, $field_size);
        html::label('password2', lang::translate('account_form_retype_password'));
        html::password('password2',  null, $field_size);
        html::label('submit', '');
        html::submit('submit', lang::translate('account_submit'));
        html::formEnd();
        echo html::getStr();
    }
    
    public static function formSend () {
        html::$autoLoadTrigger = 'submit';
        html::init($_POST);
        html::formStart('account_request_new_password');
        html::legend(lang::translate('account_request_password_title'));
        html::label('email', lang::translate('account_email_label'), array('required' => 1));
        html::text('email');
        html::label('captcha', captcha::createCaptcha());
        html::text('captcha');
        html::label('submit', '');
        html::submit('submit', lang::translate('account_submit'));
        html::formEnd();
        echo html::getStr();
    }
}