<?php

$_COS_LANG_MODULE['Search for users'] = 'Søg efter brugere';
$_COS_LANG_MODULE['Lost password'] = 'Glömt lösenordet?';
$_COS_LANG_MODULE['Create account'] = 'Opret konto';
$_COS_LANG_MODULE['account'] = 'Account';
$_COS_LANG_MODULE['Users'] = 'Användare';
$_COS_LANG_MODULE['Logout'] = 'Logout';
$_COS_LANG_MODULE['Email'] = 'Email';
$_COS_LANG_MODULE['OpenID'] = 'OpenID';
$_COS_LANG_MODULE['Facebook'] = 'Facebook';
$_COS_LANG_MODULE['Github'] = 'Github';
$_COS_LANG_MODULE['Google'] = 'Google';
$_COS_LANG_MODULE['Admin'] = 'Admin';
