<?php

$_COS_LANG_MODULE['Email login'] = 'Login med email';
$_COS_LANG_MODULE['Create account'] = 'Opret email konto';
$_COS_LANG_MODULE['Lost password'] = 'Mistet password?';
$_COS_LANG_MODULE['OpenID'] = 'OpenID';
$_COS_LANG_MODULE['Facebook'] = 'Facebook';
$_COS_LANG_MODULE['Admin'] = 'Admin';
$_COS_LANG_MODULE['account_list_users'] = 'Vis konti';
$_COS_LANG_MODULE['Account'] = 'Konto';
$_COS_LANG_MODULE['account'] = 'Konto';
$_COS_LANG_MODULE['Github'] = 'Github';
$_COS_LANG_MODULE['Search for users'] = 'Search for users';
