<?php

$_COS_LANG_MODULE['account_login_with_email'] = 'Logga in med e-post';
$_COS_LANG_MODULE['account_create_email_account'] = 'Skapa ett e-postkonto';
$_COS_LANG_MODULE['account_request_password'] = 'Glömt lösenordet?';
$_COS_LANG_MODULE['account_use_open_id'] = 'OpenID';
$_COS_LANG_MODULE['account_login_facebook'] = 'Facebook';
$_COS_LANG_MODULE['account_admin'] = 'Admin';
$_COS_LANG_MODULE['account_list_users'] = 'Andra konton';
$_COS_LANG_MODULE['Account'] = 'Account';
$_COS_LANG_MODULE['account'] = 'Account';
$_COS_LANG_MODULE['account_login_github'] = 'Github';
