<?=lang::translate('Hi')?>!

<?=lang::translate('You have connected with')?> <?=$vars['site_name']?> <?=lang::translate('because you have lost
your password')?>. <?=lang::translate('In order to create a new password just press the
following link or paste it into your browsers URL line')?>.

<?=$vars['verify_key']?>


<?=lang::translate('If you have not requested a new password then you can just delete
this message')?>.

Kind Regards <?=$vars['site_name']?>